- name: TIMESTAMP DIRECTORY
  hosts: localhost
  gather_facts: true

  tasks:  
    - name: make directory
      ansible.builtin.file:
        path: "../config-backups"
        state: directory

- name: IOS ROUTERS
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: IOS CONFIG
      ios_command:
        commands: copy run start
      register: output_router

    - name: SAVE ROUTER CONFIG
      fetch:
        src: "flash:/startup-config"
        dest: "../config-backups/show_run_{{ inventory_hostname }}.txt"

- name: IOS SWITCHES
  hosts: switches
  gather_facts: false
  connection: network_cli

  tasks:
    - name: IOS CONFIG
      ios_command:
        commands: copy run start
      register: output_switch

    - name: SAVE SWITCH CONFIG
      fetch:
        src: "flash:/startup-config"
        dest: "../config-backups/show_run_{{ inventory_hostname }}.txt"  