- name: TIMESTAMP DIRECTORY
  hosts: localhost
  gather_facts: true

  tasks:  
    - name: make directory
      ansible.builtin.file:
        path: "../config-backups/{{ ansible_date_time.date }}"
        state: directory

- name: IOS ROUTERS
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: IOS CONFIG
      ios_command:
        commands: show run
      register: output_router

    - name: SAVE ROUTER CONFIG
      copy:
        content: "{{ output_router.stdout[0] }}"
        dest: "../config-backups/{{ ansible_date_time.date }}/show_run_{{ inventory_hostname }}.txt"

- name: IOS SWITCHES
  hosts: switches
  gather_facts: false
  connection: network_cli

  tasks:
    - name: IOS CONFIG
      ios_command:
        commands: show run
      register: output_switch

    - name: SAVE SWITCH CONFIG
      copy:
        content: "{{ output_switch.stdout[0] }}"
        dest: "../config-backups/{{ ansible_date_time.date }}/show_run_{{ inventory_hostname }}.txt"  