- name: TIMESTAMP DIRECTORY
  hosts: localhost
  gather_facts: true

  tasks:  
    - name: make directory
      ansible.builtin.file:
        path: "../config-backups"
        state: directory

- name: IOS ROUTERS
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
    -name: backup running-config
    ios_config:
       backup: yes
       backup_options:
         filename: "running-config-{{ timestamp.stdout }}.txt"
         dir_path: "./config-backups/{{ inventory_hostname }}"

- name: IOS SWITCHES
  hosts: switches
  gather_facts: false
  connection: network_cli

  tasks:
    - name: backup running-config
      ios_config:
       backup: yes
       backup_options:
         filename: "running-config-{{ timestamp.stdout }}.txt"
         dir_path: "../config-backups/{{ inventory_hostname }}"